let atletas = [
    {   titulo : "Gabriel Geraldo Dos Santos Araújo",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/309-1024x713.jpg",
        modalidade : "Natação",
        localDeNascimento : "Santa Luzia – Minas Gerais",
        biografia : "Gabriel tem focomelia, doença congênita que impede a formação normal de braços e pernas, e conheceu a natação por meio de um professor de Educação Física da escola onde estudava, nos Jogos Escolares de Minas Gerais (JEMG).",
        conquistas : "Ouro nos 50m livre, 50m costas, 100m livre, 100m costas e 200m livre nos Jogos Parapan-Americanos de Santiago 2023; ouro nos 50m costas, 100m costas e nos 200m livre no Mundial de Manchester 2023; ouro nos 100m costas, 50m costas e 200m livre no Mundial da Ilha da Madeira 2022; ouro nos 200m livre e nos 50m costas e prata nos 100m costas nos Jogos Paralímpicos de Tóquio; ouro nos 50m e 100m livre, prata nos 200m livre e bronze nos 100m costas e nos 50m borboleta nos Jogos Parapan-Americanos de Lima 2019.",
        link : "https://cpb.org.br/atletas/gabriel-geraldo-dos-santos-araujo/",
        redeSocial: "https://instagram.com/gabrielaraujo_s2",
        tags: "gabrielzinho nataçao natacao "
    },
    {   titulo : "Abinaecia Maria Da Silva",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/121-768x495.jpg",
        modalidade : "Badminton",
        localDeNascimento : "Cabo de Santo Agostinho – Pernambuco",
        biografia : "Abinaecia teve poliomielite aos dois anos e meio de idade Depois de três anos, voltou a andar, mas teve atrofia e encurtamento da perna direita. Conheceu o badminton paralímpico aos 13 anos, na aula de Educação Física, quando o seu professor a viu isolada e disse que levaria um esporte que ela pudesse praticar. Sua primeira convocação para a Seleção Brasileira foi em 2017.",
        conquistas : "Ouro no simples feminino nos Jogos Parapan-Americanos de Santiago 2023; bronze na dupla misto nos Jogos Parapan-Americanos de Lima 2019.",
        link : "https://cpb.org.br/atletas/abinaecia-maria-da-silva/",
        redeSocial: "",
        tags: "raquete"
    },
    {   titulo : "Adria Jesus da Silva",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/404-768x512.jpg",
        modalidade : "Vôlei Sentado",
        localDeNascimento : "Goiânia – Goiás",
        biografia : "Em 1999, aos 16 anos, Adria sofreu um acidente de moto e teve que amputar a perna esquerda abaixo do joelho. A goianiense foi convidada por um professor de vôlei sentado para experimentar a modalidade no fim de 2005. Foi convocada pela primeira vez para a Seleção no ano seguinte.",
        conquistas : "Ouro no Mundial da Bósnia 2022; bronze nos Jogos Paralímpicos de Tóquio 2020; prata nos Jogos Parapan-Americanos Lima 2019; bronze nos Jogos Paralímpicos Rio 2016; prata nos Jogos Parapan-Americanos Toronto 2015.",
        link : "https://cpb.org.br/atletas/adria-jesus-da-silva/",
        redeSocial: "https://www.instagram.com/adriaparatleta/",
        tags: "bronze volei sentado goiania goias"
    },
    {   titulo : "Ádria Rocha Santos",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/5601715452_bf40d60912_o-768x592.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Nanuque – Minas Gerais",
        biografia : "Foi perdendo a visão aos poucos por causa de uma doença degenerativa, até ficar completamente cega em 1994.",
        conquistas : "Bronze nos 100m nos Jogos Paralímpicos em Pequim 2008; prata nos 200m e 400m nos Jogos Parapan-Americanos Brasil 2007; ouro nos 100m e prata nos 200m e 400m nos Jogos Paralímpicos Atenas 2004; ouro nos 100m, 200m e 400m no Mundial do Canadá 2003; ouro nos 200m no Mundial da França 2003; ouro nos 100m e prata nos 200m nos Jogos Parapan-Americanos Argentina 2003; prata nos 100m e 200m no Mundial da França 2002; ouro nos 200m no Mundial do Canadá 2001; ouro nos 100m e 200m e prata nos 400m nos Jogos Paralímpicos Sydney 2000; ouro nos 100m, 200m e 400m nos Jogos Parapan-Americanos México 1999; prata nos 100m, 200m e 400m nos Jogos Paralímpicos Atlanta 1996; bronze nos 200m e 400m no Mundial da Alemanha 1994; ouro nos 100m nos Jogos Paralímpicos Barcelona 1992 e prata nos 100m e 400m nos Jogos Paralímpicos Seul 1988.",
        link : "https://cpb.org.br/atletas/adria-rocha-santos/",
        redeSocial: "https://instagram.com/adriasantosatleta",
        tags: "adria corrida"
    },
    {   titulo : "Thalys Silva",
        retrato : "https://cpb.org.br/wp-content/uploads/2024/03/Thalys-Juca-768x512.jpeg",
        modalidade : "Rúgbi em Cadeira de Rodas",
        localDeNascimento : "Rio Branco – Acre",
        biografia : "Thalys nasceu com má-formação congênita nas pernas. Conheceu o esporte paralímpico em 2022 a convite de um amigo. Essa foi a primeira modalidade adaptada que ele pratica.",
        conquistas : "Bronze nos Jogos Parapan-Americanos de Santiago 2023; ouro no Campeonato Sul-Americano 2023; prata no Campeonato Brasileiro 2023.",
        link : "https://cpb.org.br/atletas/thalys-silva/",
        redeSocial: "https://www.instagram.com/coe.thalys/",
        tags: "rugbi rugby talis thalis cadeira de rodas cadeirante"
    },
    {   titulo : "Edson Cavalcante",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/22-e1690391882996-768x625.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Cruzeiro do Sul – Acre",
        biografia : "O acreano nasceu no seringal com ajuda de uma parteira. Com falta de oxigênio, teve paralisia cerebral, que prejudicou os movimentos do braço direito. Edson praticava tênis de mesa em 2001 e, um ano depois, migrou para o atletismo. Em menos de dois anos no esporte, conquistou seu lugar na Seleção Brasileira.",
        conquistas : "Ouro nos 100m nos Jogos Parapan-Americanos Lima 2019; bronze nos 100m no Mundial Londres 2017; bronze nos 100m nos Jogos Paralímpicos Rio 2016; ouro nos 100m e bronze nos 200m nos Jogos Parapan-Americanos Toronto 2015; prata nos 100m no Mundial Doha 2015; bronze nos 100m no Mundial Lyon 2013; ouro nos 100m e nos 200m e prata nos 400m nos Jogos Parapan-Americanos Guadalajara 2011; bronze nos 100m no Mundial de Christchurch 2011; ouro nos 100m e nos 200m nos Jogos Parapan-Americanos Rio 2007.",
        link : "https://cpb.org.br/atletas/edson-cavalcante-pinheiro/",
        redeSocial: "https://instagram.com/edsoncavalcantepinheiro",
        tags: ""
    },
    {   titulo : "Débora Oliveira de Lima",
        retrato : "https://cpb.org.br/wp-content/uploads/2024/06/debinha-768x512.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Rio Branco – Acre",
        biografia : "Começou no esporte aos 12 anos por indicação de um psicólogo. No início, praticou natação. Quatro anos depois, dois treinadores do clube a indicaram para o atletismo paralímpico. Lá, gostou de praticar o salto em distância, que é a sua prova principal até hoje.",
        conquistas : "Prata no salto em distância no Mundial de Kobe 2024; ouro no salto em distância no Grand Prix de Jesolo 2024; prata da mesma prova no Campeonato Brasileiro de atletismo 2023.",
        link : "https://cpb.org.br/atletas/debora-oliveira-de-lima/",
        redeSocial: "https://www.instagram.com/_debiinhaa_/",
        tags: "debinha debora"
    },
    {   titulo : "Jerusa Geber",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/38.jpg",
        modalidade : " 	Atletismo",
        localDeNascimento : "Rio Branco – Acre",
        biografia : "Jerusa nasceu totalmente cega. Ao longo da vida, fez algumas cirurgias que possibilitaram que ela enxergasse um pouco, mas aos 18 anos voltou a perder totalmente a visão. Conheceu o esporte paralímpico aos 19 anos a convite de um amigo também deficiente visual. Em 2019, Jerusa se tornou a primeira atleta cega a correr os 100m abaixo dos 12s. É a atual recordista mundial nos 100m pela classe T11 com o tempo de 11s83.",
        conquistas : "Ouro nos 100m e bronze nos 200m no Mundial de Kobe 2024; ouro nos 100m e 200m e prata no revezamento 4x100m nos Jogos Parapan-Americanos de Santiago 2023; ouro nos 100m e 200m no Mundial Paris 2023; bronze nos 200m nos Jogos Paralímpicos de Tóquio 2020; ouro nos 100m no Mundial Dubai 2019; ouro nos 100m e nos 200m nos Jogos Parapan-Americanos Lima 2019; bronze nos 100m e nos 400m nos Jogos Parapan-Americanos Toronto 2015; prata nos 100m no Mundial Doha 2015; prata nos 100m e nos 200m no Mundial Lyon 2013; prata nos 100m e nos 200m nos Jogos Paralímpicos Londres 2012; prata nos 100m e nos 200m nos Jogos Parapan-Americanos Guadalajara 2011; ouro no revezamento 4x100m, prata nos 100m e nos 200m no Mundial da Nova Zelândia 2011; bronze nos 100m nos Jogos Paralímpicos Pequim 2008.",
        link : "https://cpb.org.br/atletas/jerusa-geber-dos-santos/",
        redeSocial: "https://instagram.com/jerusaatletismo",
        tags: ""
    },
    {   titulo : "Géssica Thaís Souza De Araújo",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/410.jpeg",
        modalidade : " Vôlei Sentado",
        localDeNascimento : "Maceió – Alagoas",
        biografia : "Géssica nasceu com má formação na perna direita. Em 2016, seu atual técnico a parou na rua e a convidou para conhecer o voleibol sentado.",
        conquistas : "Prata nos Jogos Parapan-Americanos Lima 2019; ouro nos Jogos Parapan-Americanos de Jovens em 2017.",
        link : "https://cpb.org.br/atletas/gessica-thais-souza-de-araujo/",
        redeSocial: "https://instagram.com/gessica_araujoo_",
        tags: "Gessica Jessica cadeirante cadeira de rodas volei"
    },
    {   titulo : "Yohansson do Nascimento",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/95-1024x683.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Maceió – Alagoas",
        biografia : "Yohansson nasceu sem as duas mãos. Conheceu o atletismo aos 17 anos, convidado pela técnica Valquíria Campelo, no ônibus em sua cidade natal, Maceió.",
        conquistas : "Prata nos 100m nos Jogos Parapan-Americanos Lima 2019; prata nos 100m e 200m no Mundial de Londres 2017; prata no revezamento 4×100 e bronze nos 100m nos Jogos Paralímpicos Rio 2016, prata nos 200m e bronze nos 100m nos Jogos Parapan-Americanos de Toronto 2015; ouro nos 200m e prata nos 100m no Mundial de Doha (Catar) 2015; ouro nos 200m, prata no revezamento 4x100m e bronze nos 100m no Mundial de Lyon 2013; ouro nos 200m e prata nos 400m nos Jogos Paralímpicos de Londres 2012; prata no revezamento 4x100m e bronze nos 100m nos Jogos Paralímpicos de Pequim 2008; ouro nos 100m, prata nos 200m e bronze no revezamento 4x100m no Mundial de Christchurch 2011; ouro nos 100m, 200m e 400m nos Jogos Parapan-Americanos do Rio 2007.",
        link : "https://cpb.org.br/atletas/yohansson-do-nascimento-ferreira/",
        redeSocial: "https://instagram.com/yohanssonf",
        tags: "iohansson"
    },
    {   titulo : "Marivana Oliveira Da Nóbrega",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/57-740x1024.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Maceió – Alagoas",
        biografia : "Marivana teve paralisia cerebral por falta de oxigenação no cérebro, que afetou seus membros inferiores. Em 2008, ela fazia fisioterapia numa associação para pessoas com deficiência, quando uma pessoa que trabalhava com um atleta a viu e disse que ela tinha “perfil de atleta”. Num primeiro momento, ela não levou a sério e foram necessários 6 meses de insistência para ir a um treino.",
        conquistas : "Prata no arremesso de peso nos Jogos Paralímpicos de Tóquio 2020; bronze no arremesso de peso no Mundial Dubai 2019; bronze no arremesso de peso nos Jogos Parapan-Americanos Lima 2019; bronze no arremesso de peso nos Jogos Paralímpicos Rio 2016; bronze no arremesso de peso no Mundial Doha 2015.",
        link : "https://cpb.org.br/atletas/marivana-oliveira-da-nobrega/",
        redeSocial: "https://instagram.com/maryoliveiraoficial35",
        tags: ""
    },
    {   titulo : "Leylianne Samara Ramos dos Santos",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/369-1024x683.jpg",
        modalidade : "Taekwondo",
        localDeNascimento : "Macapá – Amapá",
        biografia : "Leylianne teve má-formação congênita no braço esquerdo, abaixo do cotovelo. Ela é faixa preta em karatê. Em 2018, recebeu convite para experimentar o taekwondo paralímpico. Começou na modalidade apenas no início de 2019. Foi convocada pela primeira vez para a Seleção Brasileira em abril de 2019.",
        conquistas : "Bronze na categoria até 65kg nos Jogos Parapan-Americanos de Santiago 2023; bronze no Grand Prix de Manchester 2022; bronze nos Jogos Parapan-Americanos Lima 2019; bronze no Pan-Americano da modalidade nos Estados Unidos 2019.",
        link : "https://cpb.org.br/atletas/leylianne-samara-ramos-dos-santos/",
        redeSocial: "https://instagram.com/leyliannesantos_paratkd",
        tags: "taekondo taekundo luta leiliane leilianne"
    },
    {   titulo : "Marcia Cristina De Almeida Oiveira",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/55-1024x684.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Santana – Amapá",
        biografia : "Marcia enxergava normalmente. Aos 13 anos, durante as férias do meio do ano, entrou numa piscina e ficou com os olhos extremamente irritados. “Tratou” a situação com colírio, mas sua visão piorou. Quando foi ao médico, descobriu que estava com conjuntivite e que a secreção da doença acumulou em seus olhos. Fez três cirurgias e sua visão piorou a cada uma delas. Depois da última, se tornou totalmente cega. Começou no esporte paralímpico em 2012, através do convênio pedagógico de sua cidade. Entraram em contato com ela para saber se tinha interesse em treinar goalball e atletismo. No mesmo ano, participou das Paralímpiadas Escolares nas duas modalidades.",
        conquistas : "Prata no lançamento de dardo nos Jogos Parapan-Americanos Lima 2019.",
        link : "https://cpb.org.br/atletas/marcia-cristina-de-almeida-oiveira/",
        redeSocial: "https://instagram.com/marciaatleta",
        tags: ""
    },
    {   titulo : "Wanna Brito",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/53046351070_dc33c8dab2_o-1024x651.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Macapá – Amapá",
        biografia : "Wanna teve diagnosticada paralisia cerebral no momento do parto. Começou no esporte por meio da natação no ano de 2018 e, já no final de 2019, migrou para o atletismo por incentivo do técnico Marlon Gomes. Sua primeira competição foi em 2020 e despontou no cenário paralímpico nacional após participar do Meeting Paralímpico Macapá 2022. Competiu ainda no Conexão Paralímpica, quando conquistou duas medalhas de ouro, e no Grand Prix de atletismo em Marrakech em 2023, ganhando um ouro e uma prata.",
        conquistas : "Ouro no arremesso de peso e no lançamento de club no Mundial de Kobe 2024; ouro no arremesso de peso nos Jogos Parapan-Americanos de Santiago 2023; prata no arremesso de peso no Mundial Paris 2023; ouro no arremesso de peso e prata no lançamento de club no Grand Prix de atletismo em Marrakech 2023.",
        link : "https://cpb.org.br/atletas/wanna-helena-brito-oliveira/",
        redeSocial: "https://instagram.com/wannabritoo",
        tags: "uana uanna"
    },
    {   titulo : "Elielton Lira",
        retrato : "https://cpb.org.br/wp-content/uploads/2024/03/Elielton-Oliveira-768x512.jpeg",
        modalidade : "Judô",
        localDeNascimento : "Manaus – Amazonas",
        biografia : "Elielton perdeu a visão aos 12 anos, em um acidente com arma de fogo. Começou a praticar judô em 2014. Passou a integrar a Seleção Brasileira adulta em 2022.",
        conquistas : "Prata na categoria até 60kg nos Jogos Parapan-Americanos de Santiago 2023; prata no Pan-Americano do Canadá 2022.",
        link : "https://cpb.org.br/atletas/elielton-lira/",
        redeSocial: "https://www.instagram.com/elieltonlir9/",
        tags: "judo"
    },
    {   titulo : "Lucas Manoel Galvão dos Santos",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/264-768x605.jpg",
        modalidade : "Halterofilismo",
        localDeNascimento : "Manaus – Amazonas",
        biografia : "Lucas nasceu com uma infecção no fêmur da perna direita (osteomelite), que ocasionou uma má-formação no membro. Foi convidado a iniciar a prática de halterofilismo aos 13 anos.",
        conquistas : "Ouro até 49kg nos Jogos Parapan-Americanos de Santiago 2023; bronze nos Jogos Parapan-Americanos Lima 2019; campeão mundial júnior na Cidade do México, em 2017; e prata nos Jogos Parapan-Americanos de Jovens, em São Paulo, em 2017.",
        link : "https://cpb.org.br/atletas/lucas-manoel-galvao-dos-santos/",
        redeSocial: "https://instagram.com/lucass_dos_santos.1",
        tags: "alterofilismo levantamento de peso supino"
    },
    {   titulo : "Laiana Rodrigues Batista",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/52801178463_100ee6d5a8_o-1024x689.jpg",
        modalidade : "Vôlei Sentado",
        localDeNascimento : "Manaus – Amazonas",
        biografia : "Laiana era atleta convencional de voleibol e aos 18 anos teve dengue hemorrágica e a manifestação da síndrome de Guillain Barré, doença autoimune. Suas pernas ficaram paralisadas e seu pé direito caído. Ela conheceu a modalidade paralímpica 15 anos depois, aos 33 anos.",
        conquistas : "Bronze nos Jogos Paralímpicos de Tóquio 2020; prata nos Jogos Parapan-Americanos de Lima 2019; bronze nos Jogos Paralímpicos Rio 2016; prata nos Jogos Parapan-Americanos Toronto 2015.",
        link : "https://cpb.org.br/atletas/laiana-rodrigues-batista/",
        redeSocial: "https://instagram.com/laianarodrigues12",
        tags: "volei cadeirante cadeira de rodas"
    },
    {   titulo : "Jefinho Gonçalves",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/216-683x1024.jpg",
        modalidade : "Futebol de Cegos",
        localDeNascimento : "Candeias – Bahia",
        biografia : "Aos sete anos, um glaucoma ocasionou a perda total da visão do jogador. O baiano começou na natação, passou pelo atletismo, mas se encontrou no futebol de cegos, aos 12 anos. Foi eleito o melhor jogador do mundo em 2010.",
        conquistas : "Bronze na Copa do Mundo em Birmingham 2023; tetracampeão dos Jogos Paralímpicos (Tóquio 2020, Rio 2016, Londres 2012 e Pequim 2008); prata na Copa América 2022; pentacampeão dos Jogos Parapan-Americanos (Santiago 2023, Lima 2019, Toronto 2015, Guadalajara 2011 e Rio 2007); e tricampeão Mundial (Madri 2018, Japão 2014 e Inglaterra 2010).",
        link : "https://cpb.org.br/atletas/jeferson-da-conceicao-goncalves-jefinho/",
        redeSocial: "https://instagram.com/jefinhofut5",
        tags: ""
    },
    {   titulo : "Edneusa De Jesus Santos",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/98-1024x683.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Salvador – Bahia",
        biografia : "Edneusa possui baixa visão desde o seu nascimento, decorrente de uma rubéola que sua mãe adquiriu durante a gravidez. Aos 24 anos competia no atletismo tradicional e, em 2012, passou para o atletismo paralímpico. Em sua estreia na Seleção, nos Jogos Rio 2016, Edneusa tornou-se a primeira medalhista paralímpica brasileira em maratonas.",
        conquistas : "Prata no Mundial de Maratonas de Londres 2019; bronze na maratona nos Jogos Rio 2016.",
        link : "https://cpb.org.br/atletas/edneusa-de-jesus-santos/",
        redeSocial: "https://instagram.com/edneusa.santos.1297",
        tags: ""
    },
    {   titulo : "Bruno Rodrigues Da Mota",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/366-768x576.jpg",
        modalidade : "Taekwondo",
        localDeNascimento : "Monte Santo – Bahia",
        biografia : "Bruno nasceu com má-formação no braço esquerdo. Em 2017, enquanto realizava exames de rotina, conheceu a fisioterapeuta da Seleção Brasileira, que o convidou para experimentar o parataekwondo.",
        conquistas : "",
        link : "https://cpb.org.br/atletas/bruno-rodrigues-da-mota/",
        redeSocial: "https://instagram.com/brunomottatkd",
        tags: "taekondo taekundo luta "
    },
    {   titulo : "Evânio Rodrigues Da Silva",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/260-1024x666.jpg",
        modalidade : "Halterofilismo",
        localDeNascimento : "Cícero Dantas – Bahia",
        biografia : "Teve poliomielite aos seis meses de idade, o que causou um encurtamento da perna direita. Começou a praticar halterofilismo em 2010 a convite de um amigo.",
        conquistas : "Ouro na categoria até 88kg nos Jogos Parapan-Americanos de Santiago 2023; prata na etapa de Tbilisi da Copa do Mundo 2021; ouro na Copa do Mundo da Nigéria em 2020; ouro nos Jogos Parapan-Americanos Lima 2019; prata por equipe no Mundial da modalidade no Cazaquistão em 2019; prata nos Jogos Paralímpicos Rio 2016; bronze no Mundial da Cidade do México, em 2017; e ouro nos Jogos Parapan-Americanos Toronto 2015.",
        link : "https://cpb.org.br/atletas/evanio-rodrigues-da-silva/",
        redeSocial: "https://instagram.com/evaniodasilva",
        tags: "levantamento de peso evanio"
    },
    {   titulo : "Renê Campos Pereira",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/349-768x512.jpg",
        modalidade : "Remo",
        localDeNascimento : "Itapetinga – Bahia",
        biografia : "Em 2006, o esportista e médico residente em ortopedia Renê sentiu dores na coluna. Ao procurar o hospital, foi diagnosticado com abscesso epidural, o que causou uma compressão medular e, por consequência, a perda dos movimentos das pernas. Seis anos depois, e com passagem pela natação, o baiano começou a praticar remo. Antes da lesão, ele jogou futebol em várias equipes de base da Bahia e praticou várias outras modalidades esportivas.",
        conquistas : "Bronze no single skiff masculino nos Jogos Paralímpicos de Tóquio; prata na Etapa da Copa do Mundo de Remo 2019 em Roterdã (Holanda); ouro no Campeonato Mundial de Remo Indoor; em Boston (EUA), 2017; ouro na Regata Internacional de Gavirate 2015, na Itália; ouro no Campeonato Regional de Turim 2015 (ITA); prata no Mundial Indoor de Boston 2015. ",
        link : "https://cpb.org.br/atletas/rene-campos-pereira/",
        redeSocial: "https://instagram.com/renepereiraremo",
        tags: "rene"
    },
    {   titulo : "Francisco Wellington De Melo",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/386-1024x683.jpg",
        modalidade : "Tênis de Mesa",
        localDeNascimento : "Fortaleza – Ceará",
        biografia : "Francisco teve paralisia cerebral em seu nascimento, afetando seus membros inferiores. Conheceu o tênis de mesa e em 2001 já competia.",
        conquistas : "Ouro por equipes nos Jogos Parapan-Americanos Lima 2019; ouro por equipes e bronze em individual nos Jogos Parapan-Americanos de Guadalajara 2011; bronze por equipes nos Jogos Parapan-Americanos do Rio 2007.",
        link : "https://cpb.org.br/atletas/francisco-wellington-de-melo/",
        redeSocial: "https://instagram.com/franciscowellinton",
        tags: "tenis ceara tenis raquete"
    },
    {   titulo : "Edênia Nogueira Garcia",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/302-scaled-e1690391752985-768x787.jpg",
        modalidade : "Natação",
        localDeNascimento : "Crato – Ceará",
        biografia : "Edênia nasceu com doença de Charcot-Marie-Tooth, também conhecida como atrofia fibular muscular, que afetou os movimentos dos seus membros inferiores. Começou na natação por indicação médica e foi incentivada por Francisco Avelino, que estava indo para os Jogos de Sydney 2000.",
        conquistas : "Bronze nos 50m costas nos Jogos Parapan-Americanos de Santiago 2023; prata nos 50m costas no Mundial de Manchester 2023; ouro nos 50m costas nos Mundiais de Londres 2019, Eindhoven 2010, Durban 2006 e Mar del Plata 2002. Pentacampeã parapan-americana (Mar del Plata 2003, Rio 2007, Guadalajara 2011, Toronto 2015 e Lima 2019). Medalhista de prata nos 50m costas no Mundial do México, em 2017; prata nos 50m costas nos Jogos Paralímpicos Londres 2012; bronze nos 50m livre nos Jogos Paralímpicos de Pequim 2008; ouro nos 50m livre nos Jogos Parapan-Americanos do Rio 2007; prata nos 50m costas nos Jogos Paralímpicos de Atenas 2004.",
        link : "https://cpb.org.br/atletas/edenia-nogueira-garcia/",
        redeSocial: "https://instagram.com/edeniagarciaoficial",
        tags: "edenia ceara nataçao natacao "
    },
    {   titulo : "Eugênio Franco",
        retrato : "https://cpb.org.br/wp-content/uploads/2024/03/Eugenio-Franco-e1709675577103.jpg",
        modalidade : "Tiro com Arco",
        localDeNascimento : "Beberibe – Ceará",
        biografia : "Desde 2009, apresentou sintomas e suspeita clínica de Espondilite Anquilosante que foi confirmada em 2013, com alterações osteoarticulares e comprometimento neuromuscular, sendo que a evolução da patologia foi acompanhada por outras afecções de caráter irreversível como hipertensão arterial, diabetes tipo II, artrose avançada nos membros inferiores e Doença de Parkinson desde 2016. Iniciou no tiro com arco em 2011 quando desenvolvia estágio de pós-doutorado em Portugal.",
        conquistas : "Ouro no individual W1 nos Jogos Parapan-Americanos de Santiago 2023; 1º Lugar no individual W1 e nas duplas masculinas no Campeonato de Tiro com Arco de Chicago 2023; campeão nas duplas masculinas e vice-campeão no individual do composto W1 do Parapan-Americano da modalidade em Santiago 2022; campeão brasileiro pelo composto W1 em 2021; e campeão no individual do composto W1 do ParapanAmericano da modalidade em Medellín 2019.",
        link : "https://cpb.org.br/atletas/eugenio-franco/",
        redeSocial: "https://www.instagram.com/eugenios_franco/",
        tags: "arco e flecha ceara"
    },
    {   titulo : "Maciel de Souza Santos",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/181-768x512.jpg",
        modalidade : "Bocha",
        localDeNascimento : "Crateus – Ceará",
        biografia : "Maciel nasceu com paralisia cerebral e começou na modalidade aos 11 anos. Três anos depois, passou a representar o país em competições internacionais.",
        conquistas : "Ouro no individual BC2 e por equipes BC1/BC2 nos Jogos Parapan-Americanos de Santiago 2023; ouro no individual da Copa do Mundo de bocha no Rio de Janeiro 2022; ouro por equipes na Copa América de 2021; bronze no individual nos Jogos Paralímpicos de Tóquio 2020; ouro no individual e prata por equipes nos Jogos Parapan-Americanos Lima 2019; prata nos pares nos Jogos Paralímpicos Rio 2016; ouro no individual e por equipes nos Jogos Parapan-Americanos de Toronto 2015; ouro no individual nos Jogos Paralímpicos de Londres 2012.",
        link : "https://cpb.org.br/atletas/maciel-de-souza-santos/",
        redeSocial: "https://instagram.com/macielsantosbc2",
        tags: "borcha"
    },
    {   titulo : "Oara Uchoa Assunção",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/147-768x504.jpg",
        modalidade : "Basquete em Cadeira de Rodas",
        localDeNascimento : "Fortaleza – Ceará",
        biografia : "Oara foi submetida à amputação da perna esquerda em razão de um câncer ósseo. Foi por meio do professor do professor de Educação Física da sua prima que conheceu o basquete em cadeira de rodas.",
        conquistas : "Bronze nos Jogos Parapan-Americanos de Santiago 2023; bronze nos Jogos Parapan-Americanos Lima 2019; ouro no Campeonato Sul-Americano, no Peru, em 2017; bronze na Copa das Américas em 2017.",
        link : "https://cpb.org.br/atletas/oara-uchoa-assuncao/",
        redeSocial: "https://instagram.com/oarauchaoficial",
        tags: "cadeirante ceara"
    },
    {   titulo : "Maria Fernanda",
        retrato : "https://cpb.org.br/wp-content/uploads/2024/03/Maria-Fernanda-Alves-e1711574600488-768x654.jpg",
        modalidade : "Tênis em Cadeira de Rodas",
        localDeNascimento : "Brasília – Distrito Federal",
        biografia : "Maria ficou paraplégica aos quatro anos de idade após sofrer um acidente de carro. Conheceu o esporte paralímpico aos 12 anos e já começou no tênis em cadeira de rodas. Possui seis títulos na carreira. O Parapan de Santiago 2023 foi a primeira convocação de Maria Fernanda pela Seleção Brasileira da modalidade para uma missão internacional.",
        conquistas : "Prata nas duplas femininas nos Jogos Parapan-Americanos de Santiago 2023; prata na simples na Gira Colombina 2023.",
        link : "https://cpb.org.br/atletas/maria-fernanda/",
        redeSocial: "https://www.instagram.com/mf_atleta/",
        tags: "cadeirante tenis raquete"
    },
    {   titulo : "André Claudio Botelho Dantas",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/250-768x546.jpg",
        modalidade : "Goalball",
        localDeNascimento : "Brasília – Distrito Federal",
        biografia : "Nasceu com toxoplasmose, o que afetou sua visão. Em 2009, conheceu o goalball para participar das Paralimpíadas Escolares. Gostou tanto que largou a natação, modalidade que praticava na época. A primeira convocação para a Seleção Brasileira veio no Mundial de Jovens de 2013.",
        conquistas : "Ouro nos Jogos Parapan-Americanos de Santiago 2023; bicampeão mundial (Portugal 2022 e Malmö 2018); ouro no Campeonato das Américas 2022; e ouro no Campeonato das Américas 2017.",
        link : "https://cpb.org.br/atletas/andre-claudio-botelho-dantas/",
        redeSocial: "https://instagram.com/dantas.7k",
        tags: "golbol gol bola"
    },
    {   titulo : "Amauri Alves Viana",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/154-scaled-e1690386907336-768x541.jpg",
        modalidade : "Basquete em Cadeira de Rodas",
        localDeNascimento : "Planaltina – Distrito Federal",
        biografia : "Em 2006, Amauri sofreu um acidente de carro que o deixou paraplégico. Depois de um ano e meio do ocorrido, iniciou no basquete em cadeira de rodas. O atleta chegou à Seleção Brasileira em 2012. Está desde 2014 na equipe da ADD.",
        conquistas : "Vice-campeão Sul-Americano em 2014, 2018 e 2021; quinto lugar nos Jogos Paralímpicos Rio 2016; campeão Sul-Americano em 2012.",
        link : "https://cpb.org.br/atletas/amauri-alves-viana/",
        redeSocial: "https://instagram.com/amauriiviana",
        tags: "cadeirante"
    },
    {   titulo : "Jéssica Gomes Vitorino",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/243-1024x652.jpg",
        modalidade : "Goalball",
        localDeNascimento : "Brasília – Distrito Federal",
        biografia : "Nasceu com baixa visão por causa de uma catarata congênita hereditária. Aos 16 anos, acompanhou uma apresentação da modalidade na escola e começou a praticar o esporte.",
        conquistas : "Bronze nos Jogos Parapan-Americanos de Santiago 2023; bronze nos Jogos Mundiais da IBSA 2023; ouro no Campeonato das Américas 2022; bicampeã nos Jogos Parapan-Americanos (Lima 2019 e Toronto 2015); bronze no Mundial de Goalball Malmö 2018; e prata no Campeonato das Américas 2017 em São Paulo.",
        link : "https://cpb.org.br/atletas/jessica-gomes-vitorino/",
        redeSocial: "https://instagram.com/jessica_g_vitorino",
        tags: ""
    },
    {   titulo : "Sérgio Fróes De Ribeiro Oliva",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/273-1024x683.jpg",
        modalidade : "Hipismo",
        localDeNascimento : "Brasília – Distrito Federal",
        biografia : "Sérgio teve paralisia cerebral por falta de oxigenação na incubadora. Em 1989, começou no hipismo como forma de terapia, mas ficou apenas seis meses. Depois de praticar outros esportes, aos 13 anos, o brasiliense tropeçou na saída do edifício onde morava e caiu na vidraça da portaria, cortando-se com os estilhaços. O acidente lesionou os nervos na altura das axilas e Sérgio perdeu os movimentos do braço direito. Voltou a praticar o hipismo em 2002, em provas de salto e de adestramento, onde ficou até 2005, quando optou apenas pelo adestramento.",
        conquistas : "Ouro no individual e bronze no estilo livre no Hartpury Festival of Dressage 2019, na Inglaterra; bronze no individual, no estilo livre e por equipe no Torneio de Maio em Mannheim, na Alemanha, em 2019; bronze no individual e estilo livre nos Jogos Paralímpicos Rio 2016; bronze no individual e no estilo livre no Hartpury College 2016, na Inglaterra; ouro no Mundial da Inglaterra 2007; e ouro nos Jogos Parapan-Americanos Mar del Plata 2003.",
        link : "https://cpb.org.br/atletas/sergio-froes-de-ribeiro-oliva/",
        redeSocial: "https://instagram.com/cavaleirosergiooliva",
        tags: "sergio cavalo cavalgar"
    },
    {   titulo : "Bruno Stov Kiefer",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/436-scaled-e1690388611223-768x725.jpg",
        modalidade : "Tiro Esportivo",
        localDeNascimento : "Vitória – Espírito Santo",
        biografia : "Devido à demora para nascer, o atleta ficou com paralisia cerebral que afeta os movimentos dos membros inferiores e superiores, especialmente o lado direito do corpo. Uma pessoa o abordou na rua e o convidou para praticar o tiro esportivo. Primeira convocação em fevereiro de 2018.",
        conquistas : "Bronze R4 Carabina de Ar – 10 m – posição em pé SH2 no Mundial de Lima 2023; bronze na carabina de ar 10m e 50m misto nos Jogos Parapan-Americanos Lima 2019; ouro na carabina de ar deitado e prata na em pé no Sul-Americano 2017, no Rio de Janeiro; ouro na carabina de ar em pé no Aberto Internacional 2018; ouro na carabina de ar deitado no Aberto Internacional na Colômbia em 2018.",
        link : "https://cpb.org.br/atletas/bruno-stov-kiefer/",
        redeSocial: "https://instagram.com/bruno_kiefer",
        tags: "espirito"
    },
    {   titulo : "Maxcileide De Deus Ramos",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/146-768x591.jpg",
        modalidade : "Basquete em Cadeira de Rodas",
        localDeNascimento : "Serra – Espírito Santo",
        biografia : "Maxcileide nasceu com paralisia flácida. Conheceu o esporte paralímpico em um centro de reabilitação.",
        conquistas : "Bronze nos Jogos Parapan-Americanos de Santiago 2023; bronze na Copa América 2022; bronze nos Jogos Parapan-Americanos Lima 2019; ouro no Campeonato Sul-Americano, no Peru, em 2017; bronze na Copa das Américas em 2017.",
        link : "https://cpb.org.br/atletas/maxcileide-de-deus-ramos/",
        redeSocial: "https://instagram.com/max_dramos",
        tags: "cadeirante espirito"
    },
    {   titulo : "Carlos Alberto Gomes Soares",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/197-1024x683.jpg",
        modalidade : "Ciclismo",
        localDeNascimento : "Anápolis – Goiás",
        biografia : "Aos 6 anos, Carlos foi diagnosticado com paraparesia espástica, doença que o atrapalha na locomoção. Sua perna esquerda é quase imobilizada. Antes do paraciclismo, praticava o Mountain Bike. O seu primeiro contato com o esporte paralímpico foi em 2016.",
        conquistas : "Bronze na prova de resistência na etapa da Itália e da Bélgica da Copa do Mundo de 2019.",
        link : "https://cpb.org.br/atletas/carlos-alberto-gomes-soares/",
        redeSocial: "https://instagram.com/carlosparalimpico",
        tags: "goias anapolis"
    },
    {   titulo : "Lethícia Rodrigues Lacerda",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/394-1024x683.jpg",
        modalidade : "Tênis de Mesa",
        localDeNascimento : "Goiânia – Goiás",
        biografia : "Quando tinha 14 anos, Lethícia começou a sentir dores nas pernas e dificuldade para se movimentar. Foi a muitos médicos, mas não chegaram a um diagnóstico ainda. Como ela e o irmão têm a mesma patologia, acredita-se que a causa é genética. Com o tempo, as inflamações nas articulações dos joelhos e quadril foram piorando e ela passou a usar cadeira de rodas. Sua mãe, Jane Karla, jogou tênis de mesa antes de se tornar atleta do tiro com arco. Assim, Lethícia começou a jogar tênis de mesa aos sete anos.",
        conquistas : "Bronze no individual feminino e nas duplas femininas WD14-20 nos Jogos Parapan-Americanos de Santiago 2023; prata no individual no Parapan de Jovens em Bogotá 2023; bronze no individual nos Jogos Parapan-Americanos de Lima 2019; ouro nos Jogos Parapan-Americanos de Jovens 2017 em São Paulo.",
        link : "https://cpb.org.br/atletas/lethicia-rodrigues-lacerda/",
        redeSocial: "https://instagram.com/lethicia_rodri",
        tags: "goiania goias leticia letícia lethicia tenis raquete"
    },
    {   titulo : "Teresinha (Tecka) de Jesus",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/06/Teresinha-dos-Santos-e1711652998617-768x792.jpg",
        modalidade : "Taekwondo",
        localDeNascimento : "Caxias – Maranhão",
        biografia : "Foi submetida à amputação no braço esquerdo. Conheceu o taekwondo por indicação do atleta Pedro Neves. Antes do taekwondo, foi atleta de alto rendimento do atletismo e medalhista de bronze nos Jogos Paralímpicos do Rio na corrida dos 100m.",
        conquistas : "Bronze na categoria até 47kg nos Jogos Parapan-Americanos de Santiago 2023; prata no Pan Am Series II no Brasil em 2023.",
        link : "https://cpb.org.br/atletas/teresinha-de-jesus/",
        redeSocial: "https://www.instagram.com/teckasantostkdk44/",
        tags: "taekundo taekendo taekondo maranhao"
    },
    {   titulo : "Jardiel Vieira",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/215-768x569.jpg",
        modalidade : "Futebol de Cegos",
        localDeNascimento : "Pinheiro – Maranhão",
        biografia : "Devido a toxoplasmose Jardiel nasceu cego. Por meio de um evento em São Luís (MA) para deficientes visuais, conheceu o futebol de cegos.",
        conquistas : "Ouro nos Jogos Parapan-Americanos de Santiago 2023; bronze na Copa do Mundo em Birmingham 2023; ouro nos Jogos Paralímpicos de Tóquio 2020; prata na Copa América 2022; ouro no Grand Prix México 2022; ouro no Desafio das Américas 2022; ouro nos Jogos Parapan-Americanos Lima 2019; e ouro na Copa América 2019, em São Paulo.",
        link : "https://cpb.org.br/atletas/jardiel-vieira-soares/",
        redeSocial: "https://instagram.com/jardiel.vieira",
        tags: "maranhao"
    },
    {   titulo : "Lucas Prado",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/49053263446_f9d8c024aa_o-768x596.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Poxoréu – Mato Grosso",
        biografia : "O velocista perdeu a visão em 2002, após um descolamento de retina. Em 2004, experimentou o futebol de 5, no ano seguinte, o goalball, mas se identificou mesmo com o atletismo, em 2006.",
        conquistas : "Ouro nos 100m no Mundial Dubai 2019; ouro nos 100m nos Jogos Parapan-Americanos Lima 2019; ouro no revezamento 4x100m e prata nos 100m nos Jogos Parapan-Americanos Toronto 2015; ouro nos 100m e nos 200m no Mundial Lyon 2013; prata nos 100m e nos 400m nos Jogos Paralímpicos Londres 2012; ouro nos 100m e nos 200m nos Jogos Parapan-Americanos Guadalajara 2011; ouro nos 100m, 200m e 400m no Mundial de Christchurch 2011; ouro nos 100m, 200m e 400m nos Jogos Paralímpicos Pequim 2008; ouro nos 100m, 200m e 400m nos Jogos Parapan-Americanos Rio 2007; prata nos 4x100m no Mundial de Assen 2006.",
        link : "https://cpb.org.br/atletas/lucas-prado/",
        redeSocial: "https://instagram.com/lucasprado_oficial",
        tags: "poxoreu"
    },
    {   titulo : "Samuel Eckert",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/53047078212_5553307c97_o-768x512.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Porto Alegre do Norte – Mato Grosso",
        biografia : "Aos seis meses, Samuel foi diagnosticado com toxoplasmose congênita, doença que afeta a visão. Ele conheceu o atletismo por meio de um projeto social em uma cidade vizinha.",
        conquistas : "Prata nos 800m e bronze nos 400m no Mundial de Jovens em Notwill 2017 e ouro nos 1500m e 5000m no Parapan-Americanos de Jovens 2017.",
        link : "https://cpb.org.br/atletas/samuel-eckert-de-souza/",
        redeSocial: "https://instagram.com/eckertsamuel",
        tags: ""
    },
    {   titulo : "Hebert Honório Lemes Oviedo",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/228-1024x683.jpg",
        modalidade : "Futebol PC",
        localDeNascimento : "Campo Grande – Mato Grosso do Sul",
        biografia : "Possui hemiparesia, por conta de complicações no parto, causando comprometimento no braço e perna esquerdos. Conheceu o esporte através de um professor em Campo Grande. Já foi campeão da série B e terceiro colocado na série A.",
        conquistas : "Ouro nos Jogos Parapan-Americanos Lima 2019 e bronze no Mundial da modalidade de 2019 na Espanha.",
        link : "https://cpb.org.br/atletas/hebert-honorio-lemes-oviedo/",
        redeSocial: "https://instagram.com/hebert__lemes",
        tags: ""
    },
    {   titulo : "Débora Raiza Ribeiro Benevides",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/190-1024x683.jpg",
        modalidade : "Canoagem",
        localDeNascimento : "Campo Grande – Mato Grosso do Sul",
        biografia : "A atleta tem má-formação, o que causou atrofia nas pernas. Iniciou no atletismo aos 15 anos, porém, alguns anos depois, viu que seu futuro era na água, com a canoagem.",
        conquistas : "Prata na canoa no Parapan-Americano em Halifax 2022; bronze na canoa no Mundial em Copenhague 2021; ouro no caiaque e na canoa no Campeonato Pan-Americano 2018 em Dartmonth (Canadá); prata na canoa no Mundial de Racice (República Tcheca) 2017; ouro no caiaque no Campeonato Sul-Americano de Canoagem, em Paipa 2017 (Colômbia); prata na canoa no Mundial da Alemanha 2016; bronze na canoa no Mundial de Milão 2015 (Itália).",
        link : "https://cpb.org.br/atletas/debora-raiza-ribeiro-benevides/",
        redeSocial: "https://instagram.com/debora_raiza",
        tags: "debora"
    },
    {   titulo : "Ana Carolina Moura",
        retrato : "https://cpb.org.br/wp-content/uploads/2024/03/Ana-Carolina-Moura-768x768.jpeg",
        modalidade : "Taekwondo",
        localDeNascimento : "Belo Horizonte – Minas Gerais",
        biografia : "Tem má-formação congênita do antebraço direito. Iniciou no esporte buscando uma ferramenta de autodefesa, após ser assaltada e perder um colar que sua tia deu para todas as sobrinhas quando nasceram. Antes, experimentou futebol, dança e ginástica rítmica.",
        conquistas : "Ouro na categoria até 65kg nos Jogos Parapan-Americanos de Santiago 2023; ouro no Mundial do México em 2023; bronze na etapa da França do Grand Prix em 2023; ouro no Pan Am Series II no Brasil em 2023; ouro na etapa da Arábia Saudita no Grand Prix de 2022; ouro na etapa da França do Grand Prix de 2022; bronze no Mundial da Turquia, em 2021.",
        link : "https://cpb.org.br/atletas/ana-carolina-moura/",
        redeSocial: "https://www.instagram.com/krolinamoura/",
        tags: "taikundo taekundo taekondo"
    },
    {   titulo : "Ana Cláudia Dos Santos Caldeira",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/450-1024x683.jpg",
        modalidade : "Tênis em Cadeira de Rodas",
        localDeNascimento : "Belo Horizonte – Minas Gerais",
        biografia : "Sofreu um acidente de carro em setembro de 2012 que a deixou paraplégica. O primeiro contato com o esporte paralímpico foi no Sarah Kubitschek durante a reabilitação, no basquete em cadeira de rodas. Em 2014 começou a praticar o tênis em CR após seis meses decidiu se dedicar a modalidade. Sua estreia em Jogos Paralímpicos foi em Tóquio 2020.",
        conquistas : "",
        link : "https://cpb.org.br/atletas/ana-claudia-dos-santos-caldeira/",
        redeSocial: "https://instagram.com/_anacaldeiratcr",
        tags: "tenis raquete"
    },
    {   titulo : "Harlley Damião Pereira De Arruda",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/279-1024x683.jpg",
        modalidade : "Judô",
        localDeNascimento : "Belo Horizonte – Minas Gerais",
        biografia : "Harlley perdeu a visão dos dois olhos em 1999, em um acidente com arma de fogo. Três anos após o ocorrido, foi convidado por Antônio Tenório para praticar judô.",
        conquistas : "Ouro até 73kg nos Jogos Parapan-Americanos de Santiago 2023; bronze no Pan-Americano do Canadá 2022; bronze nos Jogos Parapan-Americanos de Lima 2019, Toronto 2015 e Guadalajara 2011; bronze no Campeonato das Américas em 2018 no Canadá; e ouro no Campeonato das Américas 2017 em São Paulo.",
        link : "https://cpb.org.br/atletas/harlley-damiao-pereira-de-arruda/",
        redeSocial: "https://instagram.com/harlleyjudoca",
        tags: "harley harlei harllei judo"
    },
    {   titulo : "Thiego Marques",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/285-768x512.jpg",
        modalidade : "Judô",
        localDeNascimento : "Parauapébas – Pará",
        biografia : "Tem baixa visão por conta do albinismo. Thiego começou a praticar judô em 2011, aos 12 anos de idade.",
        conquistas : "Ouro até 60kg nos Jogos Parapan-Americanos de Santiago 2023; prata no Mundial de Baku 2022; ouro no Pan-Americano do Canadá 2022; bronze nos Jogos Parapan-Americanos Lima 2019; bronze no Campeonato das Américas 2018 no Canadá; bronze no Campeonato das Américas 2017 em São Paulo; prata no Mundial de Jovens 2013 nos Estados Unidos; e ouro nos Jogos Parapan-Americanos de Jovens 2017, em São Paulo.",
        link : "https://cpb.org.br/atletas/thiego-marques-da-silva/",
        redeSocial: "https://instagram.com/thiegomarquesjudo",
        tags: "Tiego judo"
    },
    {   titulo : "Lucicléia da Costa e Costa",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/145-768x699.jpg",
        modalidade : "Basquete em Cadeira de Rodas",
        localDeNascimento : "Salinópolis – Pará",
        biografia : "Lucicléia foi submetida à amputação das duas pernas na adolescência em razão de um câncer. Dois anos depois, a paraense conheceu o basquete em cadeira de rodas e se identificou com o esporte.",
        conquistas : "Bronze nos Jogos Parapan-Americanos de Santiago 2023; bronze nos Jogos Parapan-Americanos de Toronto 2015; bronze nos Jogos Parapan-Americanos de Guadalajara 2011.",
        link : "https://cpb.org.br/atletas/lucicleia-da-costa-e-costa/",
        redeSocial: "",
        tags: "lucicleia para cadeirante"
    },
    {   titulo : "Maria Luzineide",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/267-768x513.jpg",
        modalidade : "Halterofilismo",
        localDeNascimento : "Picuí – Paraíba",
        biografia : "Teve poliomielite aos dois anos. Começou na natação, fez cinco cirurgias nas pernas para tentar usar muletas. Em 2004, começou no halterofilismo, pois uma associação precisava de uma mulher na equipe e se apaixonou pela modalidade",
        conquistas : "Ouro nos Jogos Parapan-Americanos Lima 2019.",
        link : "https://cpb.org.br/atletas/maria-luzineide-santos-de-oliveira/",
        redeSocial: "https://instagram.com/maria.luzineide.186",
        tags: "paraiba levantamento de peso supino"
    },
    {   titulo : "Wilians Silva De Araújo",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/286-768x512.jpg",
        modalidade : "Judô",
        localDeNascimento : "Riachão do Poço – Paraíba",
        biografia : "O peso-pesado carioca perdeu a visão aos 10 anos em um acidente com tiro de espingarda e começou a praticar judô em 2009. Ele tentou, mas não se adaptou à natação e ao futebol de cegos, tendo melhor desempenho no tatame.",
        conquistas : "Prata na categoria acima de 90kg nos Jogos Parapan-Americanos de Santiago 2023; ouro nos Jogos Mundiais da IBSA 2023; ouro no Mundial de Baku 2022; ouro no Pan-Americano do Canadá 2022; ouro no Campeonato das Américas de 2020 no Canadá; prata nos Jogos Paralímpicos Rio 2016; prata nos Jogos Parapan-Americanos de Toronto 2015 e Guadalajara 2011; prata na Copa do Mundo IBSA 2018 no Cazaquistão; bronze na Copa do Mundo IBSA 2018 no Uzbequistão; bronze nos Jogos Mundiais da IBSA 2015, na Coreia do Sul, e bronze no Campeonato Mundial 2014, nos EUA.",
        link : "https://cpb.org.br/atletas/wilians-silva-de-araujo/",
        redeSocial: "https://instagram.com/wilians.araujojudo",
        tags: "wiliams judo"
    },
    {   titulo : "Mari Santilli",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/194-768x547.jpg",
        modalidade : "Canoagem",
        localDeNascimento : "Curitiba – Paraná",
        biografia : "Em 2006, Mari sofreu um acidente de moto e teve a perna esquerda amputada, na altura do joelho. Antes, ela era atleta amadora do triatlo. Após o acidente, Mari começou a fazer provas de travessia no mar e a convite de uma amiga começou a participar de competições oficiais do CPB na natação. Em 2014, migrou para a canoagem e já em 2015 foi convocada pela primeira vez para a Seleção Brasileira. Mari já disputou duas edições de Jogos Paralímpicos.",
        conquistas : "Bronze na canoa no Campeonato Mundial em Halifax 2022; ouro no caiaque e prata na canoa no Parapan-Americano em Halifax 2022.",
        link : "https://cpb.org.br/atletas/mari-santilli/",
        redeSocial: "https://instagram.com/marisantilli2011",
        tags: "parana"
    },
    {   titulo : "Carminha Celestina De Oliveira",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/202-768x563.jpg",
        modalidade : "Esgrima em Cadeira de Rodas",
        localDeNascimento : "Foz do Iguaçu – Paraná",
        biografia : "Carminha tem uma atrofia na parte inferior da perna direita por causa de uma vacina de poliomielite vencida que ela tomou quando tinha apenas três anos. Ela conheceu o Movimento Paralímpico ao assistir os Jogos Rio 2016 pela televisão. Carminha praticou o tênis de mesa antes de migrar para a esgrima.",
        conquistas : "Prata na espada no Regional das Américas em Saskatoon (Canadá) 2018.",
        link : "https://cpb.org.br/atletas/carminha-celestina-de-oliveira/",
        redeSocial: "https://instagram.com/carmemoliveira_2017",
        tags: "Carmem espada florete cadeirante parana"
    },
    {   titulo : "Eric De Oliveira Tobera",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/303-768x512.jpg",
        modalidade : "Natação",
        localDeNascimento : "Telêmaco Borba – Paraná",
        biografia : "Eric nasceu prematuro e sofreu uma paralisia cerebral. Por meio do esporte, superou a depressão e iniciou sua trajetória no atletismo. Conheceu seu atual técnico, Rui Menslin, que o convidou a treinar em Curitiba.",
        conquistas : "",
        link : "https://cpb.org.br/atletas/eric-de-oliveira-tobera/",
        redeSocial: "https://instagram.com/eric.tobera",
        tags: "erik parana nataçao natacao "
    },
    {   titulo : "Ana Cláudia",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/5-1024x653.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Recife – Pernambuco",
        biografia : "Quando tinha seis anos, Ana Cláudia sofreu uma queda e fraturou o fêmur. O ocorrido deixou a atleta sem andar. Quando chegou aos 12, conseguiu voltar a caminhar e, por intermédio de um professor de Educação Física de sua escola, começou a praticar futebol. Um tempo depois, conheceu o atletismo paralímpico e se encantou.",
        conquistas : "Prata no salto em distância nos Jogos Parapan-Americanos de Santiago 2023; bronze nos 100m no Mundial de Doha 2015.",
        link : "https://cpb.org.br/atletas/ana-claudia-maria-da-silva/",
        redeSocial: "https://instagram.com/lalaparatletape",
        tags: ""
    },
    {   titulo : "Jeohsah Beserra Dos Santos",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/36-1024x683.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Pesqueira – Pernambuco",
        biografia : "Jeohsah nasceu com uma má formação na perna esquerda. Com 12 anos, participou de sua primeira competição no atletismo: as Paralimpíadas Escolares. Os Jogos Rio 2016 marcaram a estreia do atleta na Seleção Brasileira principal da modalidade. Na ocasião, ele ficou em sexto lugar no salto em altura.",
        conquistas : "",
        link : "https://cpb.org.br/atletas/jeohsah-beserra-dos-santos/",
        redeSocial: "https://instagram.com/jeohsah",
        tags: ""
    },
    {   titulo : "Anderson Carlos Silva Ferreira",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/153-1024x683.jpg",
        modalidade : "Basquete em Cadeira de Rodas",
        localDeNascimento : "Recife – Pernambuco",
        biografia : "Aos 2 meses de nascido, Anderson teve poliomielite e suas pernas ficaram com sequela. Uma amiga o apresentou ao basquete em cadeira de rodas.",
        conquistas : "Vice-campeão no Sul-Americano na Argentina 2021; bronze nos Jogos Parapan-Americanos Rio 2007; 4° lugar nos Jogos Parapan-Americanos de Toronto 2015 e Guadalajara 2011",
        link : "https://cpb.org.br/atletas/anderson-carlos-silva-ferreira/",
        redeSocial: "https://instagram.com/andersonkings10",
        tags: "cadeirante"
    },
    {   titulo : "Luís Carlos Cardoso",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/193-768x512.jpg",
        modalidade : "Canoagem",
        localDeNascimento : "Picos – Piauí",
        biografia : "Luís era dançarino profissional e integrava o grupo de dançarinos do cantor Frank Aguiar. No final de 2009, devido a uma infecção em sua medula, perdeu os movimentos das pernas e encerrou sua carreira na dança. Pouco tempo depois, descobriu a canoagem.",
        conquistas : "Prata no caiaque no Campeonato Mundial em Halifax 2022; prata no caiaque nos Jogos Paralímpicos de Tóquio 2020; prata no caiaque no Mundial em Copenhague 2021; pentacampeão mundial na prova de canoa (Szeged 2019, Racice 2017, Duisburg 2016, Milão 2015 e Moscou 2014); ouro no caiaque na Etapa da Copa do Mundo da Polônia 2019; ouro no caiaque no Campeonato Pan-Americano 2018, em Dartmonth, no Canadá; prata na canoa e bronze no caiaque no Mundial em Manteomor-o-Velho 2018 (Portugal); prata no caiaque e na canoa na Etapa da Copa do Mundo da Hungria 2018; bronze no caiaque no Mundial de Racice (República Tcheca) 2017; ouro no caiaque no Campeonato Sul-Americano de Canoagem, em Paipa 2017, na Colômbia; bronze no caiaque no Mundial de Duisburg 2016, (Alemanha); campeão mundial no caiaque em Milão 2015 (Itália).",
        link : "https://cpb.org.br/atletas/luis-carlos-cardoso/",
        redeSocial: "https://instagram.com/luiscarlosparacanoagem",
        tags: "piaui luis"
    },
    {   titulo : "Antônia Keyla",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/7-scaled-e1690388133929-768x636.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Água Branca – Piauí",
        biografia : "Keyla foi atleta-guia da maratonista baiana Edneusa Santos, que representou o Brasil na modalidade em Mundiais e nos Jogos de Tóquio. Em 2019, teve diagnosticada a deficiência intelectual. Depois, participou de competições como os Meetings e Circuito Nacional Loterias Caixa, realizadas pelo Comitê Paralímpico Brasileiro (CPB) em todo o território do país.",
        conquistas : "Prata nos 1.500m no Mundial de Kobe 2024; prata nos 1.500m no Mundial Paris 2023; prata nos 1.500m no Global Games França 2023 (Virtus) e prata nos 800m no Grand Prix Chile 2021.",
        link : "https://cpb.org.br/atletas/antonia-keyla-da-silva-barros/",
        redeSocial: "https://instagram.com/keylabarrost20",
        tags: "antonia piaui"
    },
    {   titulo : "Michel Gomes Pessanha",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/348-1024x628.jpg",
        modalidade : "Remo",
        localDeNascimento : "Barra Mansa – Rio de Janeiro",
        biografia : "Na infância, Michel não tomou a vacina contra a poliomielite, o que lhe causou sequelas na perna e na nádega, ambas do lado direito. Com excesso de peso, o atleta começou a praticar a musculação e, consequentemente, o halterofilismo. Em 2013, o atleta fez teste na equipe de remo no Clube de Regatas do Flamengo. Foi aceito e se encontrou no esporte paralímpico.",
        conquistas : "Ouro no single skiﬀ masculino na Regata Internacional de Gavirate 2016, na Itália; prata no double skiﬀ no Mundial Indoor 2015, em Boston (EUA); bronze no double skiﬀ Misto no Mundial de Amsterdã 2014, na Holanda.",
        link : "https://cpb.org.br/atletas/michel-gomes-pessanha/",
        redeSocial: "https://instagram.com/michelpessanha_remo",
        tags: ""
    },
    {   titulo : "Brenda Freitas",
        retrato : "https://cpb.org.br/wp-content/uploads/2024/03/Brenda-Freitas--768x512.jpg",
        modalidade : "Judô",
        localDeNascimento : "Rio de Janeiro – Rio de Janeiro",
        biografia : "Brenda perdeu a visão aos 18 anos, após ter sido diagnosticada com uma herpes emocional. Começou no judô em 2018, depois de ter praticado muay thai. Ingressou na Seleção Brasileira em 2022.",
        conquistas : "Ouro nos Jogos Parapan-Americanos de Santiago 2023; bronze nos Jogos Mundiais da IBSA 2023; ouro no Pan-Americano do Canadá 2022; bronze no Mundial de Baku 2022.",
        link : "https://cpb.org.br/atletas/brenda-freitas/",
        redeSocial: "https://www.instagram.com/brendafreitasjudo/",
        tags: "judo"
    },
    {   titulo : "Luciano Bezerra Dantas",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/265-768x512.jpg",
        modalidade : "Halterofilismo",
        localDeNascimento : "Currais Novos – Rio Grande do Norte",
        biografia : "Há nove anos, quando já morava em Uberlândia, um casal de atletas paralímpicos o convidou para conhecer a modalidade. Luciano aceitou e gostou do esporte.",
        conquistas : "Prata nos Jogos Parapan-Americanos Lima 2019 e bronze nos Jogos Parapan-Americanos de Toronto 2015.",
        link : "https://cpb.org.br/atletas/luciano-bezerra-dantas/",
        redeSocial: "https://instagram.com/lucianomontanha",
        tags: "levantamento de peso"
    },
    {   titulo : "Ana Raquel Montenegro Batista Lins",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/195-768x549.jpg",
        modalidade : "Ciclismo",
        localDeNascimento : "Natal – Rio Grande do Norte",
        biografia : "Ana Raquel nasceu com síndrome de Poland, deformidade rara que afetou sua região torácica, seu braço, mão e região abdominal esquerda. Ela começou na natação e migrou para o triatlo em 2014. Participou dos Jogos Paralímpicos Rio 2016 pela modalidade e no ano seguinte, focou no paraciclismo.",
        conquistas : "",
        link : "https://cpb.org.br/atletas/ana-raquel-montenegro-batista-lins/",
        redeSocial: "https://instagram.com/anaraquellins",
        tags: ""
    },
    {   titulo : "Wallison Fortes",
        retrato : "https://cpb.org.br/wp-content/uploads/2024/06/wallison-768x576.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "São Luiz Gonzaga (RS) – Rio Grande do Sul",
        biografia : "Wallison trabalhava como mecânico e motoboy quando, em julho de 2017, sofreu um acidente de moto e foi submetido à amputação da perna direita abaixo do joelho. Iniciou na natação, mas migrou posteriormente para o atletismo.",
        conquistas : "Ouro nos 200m no Mundial de Kobe 2024; recordista brasileiro nas provas dos 100m, 200m e 400m T64.",
        link : "https://cpb.org.br/atletas/wallison-fortes/",
        redeSocial: "https://www.instagram.com/paratletafortes/",
        tags: "Sao"
    },
    {   titulo : "Geraldo Von Rosenthal",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/439-768x512.jpg",
        modalidade : "Tiro Esportivo",
        localDeNascimento : "Campo Bom – Rio Grande do Sul",
        biografia : "No tiro esportivo há mais de uma década, Geraldo Rosenthal praticava a modalidade apenas por hobby. Com má-formação congênita na mão direita, chamada de síndrome de Poland, ele não conseguia competir com atiradores convencionais. Em 2007, o gaúcho conheceu Carlos Garletti e passou a competir nos campeonatos paralímpicos. O atleta fez história na Tailândia, em 2013, ao ser o primeiro brasileiro a conquistar um ouro em uma etapa de Copa do Mundo.",
        conquistas : "Bronze na P4 Pistola 50m SH1 nos Jogos Parapan-Americanos de Santiago 2023; ouro na P4 Pistola mista – 50m – SH1 e na P1 Pistola de ar masculina – 10m – SH1, além de prata na P3 Pistola Mista – 25m – SH1 nos Jogos Parapan-Americanos de Lima 2019; ouro na pistola sport, ouro na pistola 50 metros, ouro na pistola de ar rápido e prata na pistola de ar no Aberto Internacional na Colômbia em 2018.",
        link : "https://cpb.org.br/atletas/geraldo-von-rosenthal/",
        redeSocial: "https://instagram.com/geraldorosenthal",
        tags: ""
    },
    {   titulo : "Mônica Da Silva Santos",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/204-e1690398573710-768x737.jpg",
        modalidade : "Esgrima em Cadeira de Rodas",
        localDeNascimento : "Santo Antônio da Patrulha – Rio Grande do Sul",
        biografia : "Mônica perdeu o movimento das pernas em 2002 por conta de um angioma medular que se manifestou durante a gravidez. Após o parto, ficou paraplégica e passou a jogar basquete em cadeira de rodas. Como não tinha equipe feminina, jogava com os homens. Foi então que procurou um esporte individual e encontrou a esgrima em 2008.",
        conquistas : "Ouro no florete e bronze na espada no Regional das Américas 2016, em São Paulo; ouro no florete no Regional das Américas 2015, em Montreal (primeira mulher brasileira a ser campeã de um torneio internacional).",
        link : "https://cpb.org.br/atletas/monica-da-silva-santos/",
        redeSocial: "https://instagram.com/monicamonstrinha",
        tags: "monica florete espada"
    },
    {   titulo : "Vanderson Luis Da Silva Chaves",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/205-1024x683.jpg",
        modalidade : "Esgrima em Cadeira de Rodas",
        localDeNascimento : "Porto Alegre – Rio Grande do Sul",
        biografia : "Em 2008, Vanderson sofreu um acidente com arma de fogo.",
        conquistas : "Prata no florete no Campeonato das Américas em 2016 e 2018; bronze na espada no Campeonato das Américas em 2016.",
        link : "https://cpb.org.br/atletas/vanderson-luis-da-silva-chaves/",
        redeSocial: "https://instagram.com/vanhderson_chaves",
        tags: "espada florete"
    },
    {   titulo : "Ketyla Paula Pereira Teodoro",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/48-scaled-e1690396584540-768x677.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Rolim de Moura – Rondônia",
        biografia : "Ketyla tem a doença de stargardt, doença genética que afeta a retina. Ela enxergou até os 13 anos, quando sua visão piorou rapidamente até ela se tornar baixa visão. A atleta conheceu o esporte paralímpico no último ano do ensino médio, quando um treinador de um clube em Rondônia buscava atletas para participar das Paralímpiadas Escolares de 2012.",
        conquistas : "Bronze nos 400m no Mundial de Kobe 2024; bronze nos 400m nos Jogos Parapan-Americanos de Lima 2019.",
        link : "https://cpb.org.br/atletas/ketyla-paula-pereira-teodoro/",
        redeSocial: "https://instagram.com/ketylateodoro",
        tags: "ketila"
    },
    {   titulo : "Mateus Evangelista",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/53047599133_f23f05d5e3_o-scaled-e1690398342547-768x549.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Porto Velho – Rondônia",
        biografia : "Na hora do parto, Mateus teve falta de oxigenação no cérebro e, como sequela, o lado direito de seu corpo ficou comprometido. Aos 12 anos, assistiu a uma palestra sobre esporte paralímpico em sua escola. Decidiu falar com os responsáveis para conhecer as modalidades e começou no atletismo.",
        conquistas : "Bronze no salto em distância no Mundial de Kobe 2024; bronze no salto em distância nos Jogos Paralímpicos de Tóquio 2020; prata no salto em distância no Mundial Dubai 2019; ouro nos 100m, prata nos 200m e no salto em distância nos Jogos Parapan-Americanos Lima 2019; ouro nos 100m, prata nos 200m e prata no salto em distância no Mundial Londres 2017; prata no salto em distância nos Jogos Paralímpicos Rio 2016; ouro nos 100m, nos 200m e no salto em distância nos Jogos Parapan-Americanos Toronto 2015.",
        link : "https://cpb.org.br/atletas/mateus-evangelista-cardoso/",
        redeSocial: "https://instagram.com/mateusvangelista",
        tags: ""
    },
    {   titulo : "Ymanitu Geon da Silva",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/456-768x512.jpg",
        modalidade : "Tênis em Cadeira de Rodas",
        localDeNascimento : "Tijucas – Santa Catarina",
        biografia : "Ymanitu sofreu um acidente de carro em 2007 e ficou tetraplégico. Durante a reabilitação, conheceu o tênis em cadeira de rodas e se encantou, a qual passou a dedicar-se profissionalmente. Já são 56 títulos na carreira e é o único brasileiro a disputar todos os Grand Slams da modalidade, tendo conquistado os vice-campeonatos de duplas em Roland Garros 2022 e no Australian Open 2023.",
        conquistas : "Prata nas duplas masculinas nos Jogos Parapan-Americanos de Santiago 2023; bronze na categoria quad do Campeonato Mundial de Portugal 2022; vice-campeão nas duplas em Roland Garros 2022; quinto lugar nos Jogos Paralímpicos do Rio em 2016 e ouro no individual e prata nas duplas no Campeonato Sul-Americano do Chile em 2014.",
        link : "https://cpb.org.br/atletas/ymanitu-geon-da-silva/",
        redeSocial: "https://instagram.com/ymanitu",
        tags: "tenis raquete"
    },
    {   titulo : "Larissa Rodrigues",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/319-768x519.jpg",
        modalidade : "Natação",
        localDeNascimento : "Guaraciaba – Santa Catarina",
        biografia : "Larissa tem má-formação congênita nos quatro membros. Ela praticou xadrez e arremesso de peso antes de se encontrar nas piscinas. Por meio de uma professora começou na natação paralímpica.",
        conquistas : "Bronze nos 150m medley e nos 200m livre no Mundial da Ilha da Madeira 2022.",
        link : "https://cpb.org.br/atletas/larissa-rodrigues/",
        redeSocial: "https://instagram.com/larissarodrigues3093",
        tags: "nataçao natacao "
    },
    {   titulo : "Bruno Pinheiro Carra",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/258-768x558.jpg",
        modalidade : "Halterofilismo",
        localDeNascimento : "Salto – São Paulo",
        biografia : "Bruno tem nanismo e em 2009 conheceu o halterofilismo.",
        conquistas : "Ouro na categoria até 54kg e bronze na equipe mista nos Jogos Parapan-Americanos de Santiago 2023; prata na Copa do Mundo de Dubai 2022; prata na etapa de Tbilisi da Copa do Mundo 2021; prata na Copa do Mundo da Nigéria em 2020; ouro nos Jogos Parapan-Americanos Lima 2019; prata por equipe no Mundial da modalidade no Cazaquistão em 2019; quarto lugar nos Jogos Paralímpicos Rio 2016; prata nos Jogos Parapan-Americanos Toronto 2015 e Guadalajara 2011.",
        link : "https://cpb.org.br/atletas/bruno-pinheiro-carra/",
        redeSocial: "https://instagram.com/bubulift",
        tags: "levantamento de peso sao paulo"
    },
    {   titulo : "Alana Martins Maldonado",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/275-scaled-e1690386616803-768x692.jpg",
        modalidade : "Judô",
        localDeNascimento : "Tupã – São Paulo",
        biografia : "Descobriu a doença de Stargardt aos 14 anos. Já praticava judô desde os quatro, mas, somente em 2014, quando entrou para a faculdade, começo no judô paralímpico. Líder do ranking mundial de sua categoria.",
        conquistas : "Ouro no Mundial de Baku 2022; ouro nos Jogos Paralímpicos de Tóquio 2020; prata nos Jogos Parapan-Americanos de Lima 2019; ouro no Campeonato Mundial 2018 em Portugal; prata na Copa do Mundo 2018 na Turquia; ouro na Copa do Mundo 2019 e 2017 no Uzbequistão; prata nos Jogos Paralímpicos Rio 2016; bronze nos Jogos Mundiais da IBSA 2015 na Coreia do Sul; prata nos Jogos Parapan-Americanos Toronto 2015.",
        link : "https://cpb.org.br/atletas/alana-martins-maldonado/",
        redeSocial: "https://instagram.com/alanamaldonadooficial",
        tags: "tupa judo"
    },
    {   titulo : "Jair Henrique Souza",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/34-768x521.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Araçatuba – São Paulo",
        biografia : "Jair possui nanismo. Ele conheceu o esporte paralímpico aos 15 anos por meio de um tio cadeirante que treinava atletismo.",
        conquistas : "Ouro no lançamento de dardo e bronze no arremesso de peso nos Jogos Parapan-Americanos Lima 2019.",
        link : "https://cpb.org.br/atletas/jair-henrique-souza/",
        redeSocial: "https://instagram.com/ojairzin",
        tags: "sao paulo"
    },
    {   titulo : "Carlos Antônio Dos Santos",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/103-1024x675.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Ubirajara – São Paulo",
        biografia : "Competidor de provas de fundo desde 2002, passou a ser atleta-guia em 2008 após um convite do atleta Aurélio Guedes. Atualmente concilia corridas de rua no convencional com competições como atleta guia. Nos Jogos de Tóquio, ele foi um dos guias do fundista Yeltsin Jacques.",
        conquistas : "",
        link : "https://cpb.org.br/atletas/carlos-antonio-dos-santos/",
        redeSocial: "https://instagram.com/atletabira",
        tags: "antonio sao paulo"
    },
    {   titulo : "Zileide Cassiano",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/53049951007_bb26f4c7ef_o-1-768x619.jpg",
        modalidade : "Atletismo",
        localDeNascimento : "Ribeirão Preto – São Paulo",
        biografia : "Zileide teve diagnosticada a deficiência intelectual aos seis anos de idade. Descobriu o esporte paralímpico por incentivo de um treinador da sua cidade. Começou a competir pelo salto em distância em competições regionais do interior de São Paulo.",
        conquistas : "Ouro no salto em distância no Mundial de Kobe 2024; prata no salto em distância no Mundial Paris 2023.",
        link : "https://cpb.org.br/atletas/zileide-cassiano-da-silva/",
        redeSocial: "https://instagram.com/zileidecassianot20",
        tags: "ribeirao preto sao paulo"
    },
    {   titulo : "Maria Gilda",
        retrato : "https://cpb.org.br/wp-content/uploads/2024/03/MARIA-GILDA-ANTUNES.2-768x494.jpeg",
        modalidade : "Badminton",
        localDeNascimento : "Capela – Sergipe",
        biografia : "Teve poliomielite com um ano e meio de idade. Conheceu o badminton por meio de um projeto na Universidade Federal do Sergipe.",
        conquistas : "Prata no individual feminino WH2 e bronze nas duplas femininas WH1-WH2 nos Jogos Parapan-Americanos de Santiago 2023; prata no Pan-Americano nas chaves de simples feminina WH2 em 2022 na Colômbia; ouro na dupla mista e bronze na dupla feminina no Pan-Americano na Colômbia, em 2016.",
        link : "https://cpb.org.br/atletas/maria-gilda/",
        redeSocial: "https://www.instagram.com/mariagildas/",
        tags: "raquete"
    },
    {   titulo : "Ítalo Gomes",
        retrato : "https://cpb.org.br/wp-content/uploads/2023/07/312-768x515.jpg",
        modalidade : "Natação",
        localDeNascimento : "Porto Nacional – Tocantins",
        biografia : "Durante a gravidez, a mãe de Ítalo teve rubéola, que afetou o bebê e causou uma má formação congênita. Desde criança, por conta de bronquite recebeu indicação médica para praticar natação.",
        conquistas : "Prata nos 100m costas no Jogos Parapan-Americanos Lima 2019; bronze nos 100m costas nos Jogos Paralímpicos Rio 2016; ouro nos 100m costas no Mundial de 2017 no México; ouro nos 100m costas nos Jogos Parapan-Americanos de Toronto 2015.",
        link : "https://cpb.org.br/atletas/italo-gomes-pereira-lima/",
        redeSocial: "https://instagram.com/igpl95",
        tags: "nataçao natacao italo"
    },
    // {   titulo : "",
    //     retrato : "",
    //     modalidade : "",
    //     localDeNascimento : "",
    //     biografia : "",
    //     conquistas : "",
    //     link : "",
    //     redeSocial: "",
    //     tags: ""
    // },

];
